[COURSERA] Peer Assessments /Getting and Cleaning Data Project - README
==============================================================
Class by:  Jeff Leek

Students: Hanafi

Date: April 2014

-----
# About project
Source: https://class.coursera.org/getdata-002/human_grading/view/courses/972080/assessments/3/submissions

Extracted from the source URL:

*The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis.*

-----
# Purpose
- Providing list and description of files needed to accomplished the above Coursera assesment. 

-----
# Files

1. **README.md:** This document.
1. **run_analysis.R:** A full R script to answer Peer Assesment questions.
1. **CodeBook.md:** A code book that describes the variables, the data, and any transformations or work that you performed to clean up the data
1. **"UCI HAR Dataset" folder:** This folder contains the extracted data set used in running run_analysis.R. 


## README.md
Please see purpose.

## run_analysis.R
- This files contains full script of R code to answer the question.
- Just open the files and run the full script.
- The end results of tinydata are captured under 'tinydata' data frame. This is not saved. If needed, you may save it to any directory.
- Also, the files are coming with comments to understand further on what the code is doing.
- As a pre-requisite, data folder as per question is needed to be stored in respective directory **(UCI HAR Dataset/...)**

## CodeBook.md
- This document describe the variables, the data, and any transformations or work that has been performed to clean up the data.

## "UCI HAR Dataset" folder
- Copy the entire folder into respective directory.
- Set the proper path to read the contents used in **run_analysis.R**
- Please read **UCI HAR Dataset/README.txt** to understand the details of the data.

### [End of document]
